package info.shelfunit.contact.hibernate;

import java.util.Date;

/**
 * ContactEmail generated by hbm2java
 */
public class ContactEmail  implements java.io.Serializable {


     private Integer emailCounter;
     private int version;
     private int contactCounter;
     private String emailAddress;
     private String isPrimary;
     private String isActive;
     private Date datestamp;

    public ContactEmail() {
    }

	
    public ContactEmail(int contactCounter, String emailAddress, Date datestamp) {
        this.contactCounter = contactCounter;
        this.emailAddress = emailAddress;
        this.datestamp = datestamp;
    }
    public ContactEmail(int contactCounter, String emailAddress, String isPrimary, String isActive, Date datestamp) {
       this.contactCounter = contactCounter;
       this.emailAddress = emailAddress;
       this.isPrimary = isPrimary;
       this.isActive = isActive;
       this.datestamp = datestamp;
    }
   
    public Integer getEmailCounter() {
        return this.emailCounter;
    }
    
    public void setEmailCounter(Integer emailCounter) {
        this.emailCounter = emailCounter;
    }
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    public int getContactCounter() {
        return this.contactCounter;
    }
    
    public void setContactCounter(int contactCounter) {
        this.contactCounter = contactCounter;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(String isPrimary) {
        this.isPrimary = isPrimary;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        if ( !isActive.equals( "y" ) && !isActive.equals( "n" ) ) {
            this.isActive = "n";
        }
        this.isActive = isActive;
    }
    public Date getDatestamp() {
        return this.datestamp;
    }
    
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }




}


