package info.shelfunit.contact.hibernate;

import java.util.Date;


/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer contactCounter;
     private int version;
     private String firstName;
     private String lastName;
     private String isActive;
     private Date datestamp;
     

    public Contact() {
    }

	
    public Contact(String firstName, String lastName, Date datestamp) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.datestamp = datestamp;
    }
    public Contact(String firstName, String lastName, String isActive, Date datestamp) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.isActive = isActive;
       this.datestamp = datestamp;
    }
   
    public Integer getContactCounter() {
        return this.contactCounter;
    }
    
    public void setContactCounter(Integer contactCounter) {
        this.contactCounter = contactCounter;
    }
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        if ( !isActive.equals( "y" ) && !isActive.equals( "n" ) ) {
            this.isActive = "n";
        }
        this.isActive = isActive;
    }
    public Date getDatestamp() {
        return this.datestamp;
    }
    
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }
    
    

} // end class Contact


