package info.shelfunit.contact.hibernate;

import java.util.Date;

/**
 * ContactPhone generated by hbm2java
 */
public class ContactPhone  implements java.io.Serializable {


     private Integer phoneCounter;
     private int version;
     private int contactCounter;
     private String phoneNumber;
     private String isPrimary;
     private String isActive;
     private Date datestamp;

    public ContactPhone() {
    }

	
    public ContactPhone(int contactCounter, String phoneNumber, Date datestamp) {
        this.contactCounter = contactCounter;
        this.phoneNumber = phoneNumber;
        this.datestamp = datestamp;
    }
    public ContactPhone(int contactCounter, String phoneNumber, String isPrimary, String isActive, Date datestamp) {
       this.contactCounter = contactCounter;
       this.phoneNumber = phoneNumber;
       this.isPrimary = isPrimary;
       this.isActive = isActive;
       this.datestamp = datestamp;
    }
   
    public Integer getPhoneCounter() {
        return this.phoneCounter;
    }
    
    public void setPhoneCounter(Integer phoneCounter) {
        this.phoneCounter = phoneCounter;
    }
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    public int getContactCounter() {
        return this.contactCounter;
    }
    
    public void setContactCounter(int contactCounter) {
        this.contactCounter = contactCounter;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(String isPrimary) {
        this.isPrimary = isPrimary;
    }
    public String getIsActive() {
        if ( !isActive.equals( "y" ) && !isActive.equals( "n" ) ) {
            this.isActive = "n";
        }
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Date getDatestamp() {
        return this.datestamp;
    }
    
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }




}


