package info.shelfunit.contact.hibernate;

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userCounter;
     private int version;
     private String userName;
     private String password;
     private String hintString;
     private String emailAddress;
     private String isAdmin;
     private String isActive;
     private Date datestamp;

    public User() {
    }

	
    public User(String userName, String password, Date datestamp) {
        this.userName = userName;
        this.password = password;
        this.datestamp = datestamp;
    }
    public User(String userName, String password, String hintString, String emailAddress, String isAdmin, String isActive, Date datestamp) {
       this.userName = userName;
       this.password = password;
       this.hintString = hintString;
       this.emailAddress = emailAddress;
       this.isAdmin = isAdmin;
       this.isActive = isActive;
       this.datestamp = datestamp;
    }
   
    public Integer getUserCounter() {
        return this.userCounter;
    }
    
    public void setUserCounter(Integer userCounter) {
        this.userCounter = userCounter;
    }
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getHintString() {
        return this.hintString;
    }
    
    public void setHintString(String hintString) {
        this.hintString = hintString;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(String isAdmin) {
        this.isAdmin = isAdmin;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Date getDatestamp() {
        return this.datestamp;
    }
    
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }




}


